services:
  backend:
    build: ./backend
    container_name: legallink_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - legallink_network

  frontend:
    build: ./frontend
    container_name: legallink_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - legallink_network

networks:
  legallink_network:
    driver: bridge