services:
  backend:
    build: ./backend
    container_name: legallink_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   # 👈 THIS IS THE FIX
    networks:
      - legallink_network

  frontend:
    build: ./frontend
    container_name: legallink_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - legallink_network

networks:
  legallink_network:
    driver: bridge